module.exports = {
  states: {
    Alabama: { postal: 'AL', FIPS: '01' },
    Alaska: { postal: 'AK', FIPS: '02' },
    Arizona: { postal: 'AZ', FIPS: '04' },
    Arkansas: { postal: 'AR', FIPS: '05' },
    California: { postal: 'CA', FIPS: '06' },
    Colorado: { postal: 'CO', FIPS: '08' },
    Connecticut: { postal: 'CT', FIPS: '09' },
    Delaware: { postal: 'DE', FIPS: '10' },
    Florida: { postal: 'FL', FIPS: '12' },
    Georgia: { postal: 'GA', FIPS: '13' },
    Hawaii: { postal: 'HI', FIPS: '15' },
    Idaho: { postal: 'ID', FIPS: '16' },
    Illinois: { postal: 'IL', FIPS: '17' },
    Indiana: { postal: 'IN', FIPS: '18' },
    Iowa: { postal: 'IA', FIPS: '19' },
    Kansas: { postal: 'KS', FIPS: '20' },
    Kentucky: { postal: 'KY', FIPS: '21' },
    Louisiana: { postal: 'LA', FIPS: '22' },
    Maine: { postal: 'ME', FIPS: '23' },
    Maryland: { postal: 'MD', FIPS: '24' },
    Massachusetts: { postal: 'MA', FIPS: '25' },
    Michigan: { postal: 'MI', FIPS: '26' },
    Minnesota: { postal: 'MN', FIPS: '27' },
    Mississippi: { postal: 'MS', FIPS: '28' },
    Missouri: { postal: 'MO', FIPS: '29' },
    Montana: { postal: 'MT', FIPS: '30' },
    Nebraska: { postal: 'NE', FIPS: '31' },
    Nevada: { postal: 'NV', FIPS: '32' },
    'New Hampshire': { postal: 'NH', FIPS: '33' },
    'New Jersey': { postal: 'NJ', FIPS: '34' },
    'New Mexico': { postal: 'NM', FIPS: '35' },
    'New York': { postal: 'NY', FIPS: '36' },
    'North Carolina': { postal: 'NC', FIPS: '37' },
    'North Dakota': { postal: 'ND', FIPS: '38' },
    Ohio: { postal: 'OH', FIPS: '39' },
    Oklahoma: { postal: 'OK', FIPS: '40' },
    Oregon: { postal: 'OR', FIPS: '41' },
    Pennsylvania: { postal: 'PA', FIPS: '42' },
    'Rhode Island': { postal: 'RI', FIPS: '44' },
    'South Carolina': { postal: 'SC', FIPS: '45' },
    'South Dakota': { postal: 'SD', FIPS: '46' },
    Tennessee: { postal: 'TN', FIPS: '47' },
    Texas: { postal: 'TX', FIPS: '48' },
    Utah: { postal: 'UT', FIPS: '49' },
    Vermont: { postal: 'VT', FIPS: '50' },
    Virginia: { postal: 'VA', FIPS: '51' },
    Washington: { postal: 'WA', FIPS: '53' },
    'West Virginia': { postal: 'WV', FIPS: '54' },
    Wisconsin: { postal: 'WI', FIPS: '55' },
    Wyoming: { postal: 'WY', FIPS: '56' },
    'American Samoa': { postal: 'AS', FIPS: '60' },
    Guam: { postal: 'GU', FIPS: '66' },
    'Northern Mariana Islands': { postal: 'MP', FIPS: '69' },
    'Puerto Rico': { postal: 'PR', FIPS: '72' },
    'Virgin Island': { postal: 'VI', FIPS: '78' },
  },
};
